services:
  anna:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anna-bot
    restart: unless-stopped
    env_file:
      - .env

    network_mode: "host"

    volumes:
      - ./reminders.json:/app/reminders.json
    # Optional: limit resources
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '1.5'
